def detalhe_raca():
    print("1 - Humano :\n\nOs humanos são a mais jovem das raças comuns, chegando mais tarde no cenário mundial e com uma vida curta, se comparados aos anões, elfos e dragões. Talvez seja por causa de suas vidas mais curtas que eles se esforcem para alcançar o máximo que podem nos anos que têm. O que quer que os motive, os humanos são os inovadores, os realizadores e os pioneiros dos mundos.\n")
    print("Bônus de raça : +1 em todos os atributos\n")
    print("2 - Elfo :\n\nElfos são um povo mágico de graça sobrenatural, vivendo no mundo sem pertencer inteiramente à ele. Eles vivem em lugares de beleza etérea, no meio de antigas florestas ou em torres prateadas brilhando com luz feérica, onde uma música suave ecoa através do ar e fragrâncias suaves flutuam na brisa. Esbeltos e graciosos, os elfos amam a natureza e a magia, a arte e o estudo, a música e a poesia, e as coisas boas do mundo.\n")
    print("Bônus de raça : +3 em inteligência, +2 em magia e +1 em destreza\n")
    print("3 - Anão :\n\nReinos ricos de antiga grandeza, salões esculpidos nas raízes das montanhas, o eco de picaretas e martelos nas minas profundas e nas forjas ardentes, um compromisso com o clã e a tradição, e um ódio impetuoso contra goblins e orcs, linhas comuns unem todos os anões. Baixos e robustos, os anões são conhecidos como hábeis guerreiros, mineradores e trabalhadores em pedra e metal.\n")
    print("Bônus de raça : +3 em força e +2 em defesa\n")
    print("4 - Meio-Orc :\n\nTribos orcs e humanas as vezes formam alianças e quando essas são seladas através do casamento, os meio-orcs nascem. Qualquer meio-orc que tenha vivido entre ou próximo de orcs terá cicatrizes, independentemente de serem marcas de humilhação ou de orgulho, recontando suas façanhas e ferimentos do passado. A pigmentação acinzentada dos meio-orcs, suas testas avantajadas, mandíbulas salientes, dentes proeminentes e corpos grandes torna sua herança orc notável para todos os observadores.\n")
    print("Bônus de raça : +4 em força, +3 em defesa e -1 em inteligencia e magia.\n")

def detalhe_classe():
    print("1 - Guerreiro :\n\n Guerreiros aprendem o básico de todos os estilos de combate. Todo guerreiro sabe brandir um machado, esgrimir com uma rapieira, empunhar uma espada longa ou uma espada grande, usar um arco ou mesmo prender inimigos em uma rede com algum grau de perícia. Da mesma forma, um guerreiro sabe usar escudos e qualquer tipo de armadura.\n")
    print("Atributos da classe : +2 em força, +1 em defesa e -1 em agilidade e magia.\n")
    print("2 - Ladino :\n\nLadinos dedicam muito de seus recursos para se tornarem mestres em várias perícias, bem como aperfeiçoar suas habilidades em combate, adquirindo uma vasta experiência que poucos personagens podem alcançar. Muitos ladinos focam na furtividade e trapaça, enquanto outros refinam suas perícias para ajudá-los nas masmorras, como escalada, encontrar e desarmar armadilhas, e abrir fechaduras.\n")
    print("Atributos da classe : +3 em destreza e +2 em agilidade.\n")
    print("3 - Mago :\n\nMagos vivem e morrem por suas magias. Todo o resto é secundário. Eles aprendem novas magias à medida que eles experimentam e crescem em experiência. Embora, conjurar uma magia básica requeira meramente a pronúncia de algumas palavras estranhas, gestos fugazes, e às vezes um punhado ou um grupo de materiais exóticos, esses materiais mal denotam a experiência alcançada após anos de aprendizagem e incontáveis horas de estudo.\n")
    print("Atributos da classe : +3 em magia, +2 em inteligencia e -1 em força.\n")
    print("4 - Paladino :\n\nUm paladino jura defender a justiça e integridade, se manter com as coisas boas do mundo contra a invasão das trevas e caçar as forças do mal onde quer que ela se esconda. Os paladinos treinam por anos para aprender as perícias de combate, dominando uma variedade de armas e armaduras. Mesmo assim, suas perícias marciais são secundárias ao poder mágico que ele empunha: o poder de curar os doentes e feridos, de destruir os cruéis e os mortos-vivos e de proteger os inocentes e aqueles que se unirem a eles na luta pela justiça.\n")
    print("Atributos da classe : +3 em defesa e +2 em força e magia.\n")
